# Generated by Django 6.0.3 on 2026-03-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tecnologia', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('url_github', models.URLField(blank=True)),
                ('url_demo', models.URLField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
